# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Installing Dependencies
          command: |
            mkdir -p /tmp/artifacts/coverage
            mkdir -p /tmp/phpunit
            composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      # run tests!
      - run:
          name: Running Unit Tests
          command: vendor/bin/phpunit --log-junit /tmp/phpunit/junit.xml --coverage-clover=/tmp/phpunit/clover.xml --coverage-html=/tmp/artifacts/coverage

      - run:
          name: Check 100% Test Coverage
          command: php coverage.php /tmp/phpunit/clover.xml 100

      - store_artifacts:
          path: /tmp/artifacts

      - store_test_results:
          path: /tmp/phpunit
